CC=g++ #creates variable CC for gcc compiling
CFLAGS= -c -Wall #stores options to pass to the c compiler. -c is for compiling into an object and -wall is for compiler warnings

all: task1 task2 #running make builds the program

task1.o: task1.c #shows isEven.o is dependent on isEven.c and creates main object
	$(CC) $(CFLAGS) task1.c -o task1
#compiles isEven.c and checks for common compiler warnings

task2.o: task2.c #shows isOdd.o is dependent on isOdd.c and creates main object
	$(CC) $(CFLAGS) task2.c -o task2
#compiles isOdd.c and checks for common compiler warnings

clean:
	rm -f *.o prog
#deletes object files and executable files, but leaves source code untouched